//actionType
//home页面
const INIT = "INIT";
const INIT_SUCCESS = "INIT_SUCCESS";
const GET_SWIPER = "GET_SWIPER";
const GET_PANELDATA = "GET_PANELDATA";
const GET_RANKLIST = "GET_RANKLIST";
const FETCH_REQUEST = "FETCH_REQUEST";
const FETCH_SUCCESS = "FETCH_SUCCESS";
const FETCH_ERROR = "FETCH_ERROR";
//music
const ADD_MUSIC = "ADD_MUSIC";
const PLAY_LAST = "PLAY_LAST";
const CHANGE_MUSICLIST="CHANGE_MUSICLIST";
export default {
	INIT,INIT_SUCCESS,FETCH_REQUEST,FETCH_SUCCESS,FETCH_ERROR,
	ADD_MUSIC,PLAY_LAST,CHANGE_MUSICLIST
}